
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8085:8085"
    networks:
      - app-network
    depends_on:
      - mysql

  frontend:
    build:
      context: ./chat-app
    ports:
      - "8081:8080"
    networks:
      - app-network
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    container_name: mysql-chat-app
    environment:
      MYSQL_ROOT_PASSWORD: chatapp99
      MYSQL_DATABASE: chatapp
    networks:
      - app-network
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  python-service:
    build:
      context: ./py-service
    ports:
      - "5001:5001"
    networks:
      - app-network
    depends_on:
      - mysql

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
