

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./chat-app
    ports:
      - "8081:8080"  # Expose frontend on port 8081 on the host
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
