spring.application.name=chat-app

server.port=8085

spring.jpa.hibernate.ddl-auto=create
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Update the MySQL database connection URL to use the Docker service name 'mysql'
spring.datasource.url=jdbc:mysql://mysql:3306/chatapp?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=chatapp99

# JPA vendor adapter configuration
spring.jpa.properties.hibernate.jpa.entitymanager_factory.interface=jakarta.persistence.EntityManagerFactory
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
